mongodb.host=localhost
mongodb.port=27017
mongodb.username=master
mongodb.password=debuggeandoideas
mongodb.database=catalog
mongodb.authentication-database=admin

mongodb.max.PoolSize=100
mongodb.min.PoolSize=10

mongodb.maxConnectionLifeTime=60000

#spring.data.mongodb.auto-index-creation=true